# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Computational Toxicology"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "nanhung"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	name = "Nan-Hung Hsieh"
	description = "Describe your website"
	job = "Computational Toxicology"
	bio = "Pharmacometrics | Bayesian | Risk"
	# Enter optionally your twitter account
	twitter = "nanhung5"
	enableRSS = true
	enableDisqus = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "Powered by [HUGO](https://gohugo.io/) and [blogdown](https://github.com/rstudio/blogdown)"
	# Sharing options and author information in posts
	aboutAuthor = "Computational Toxicology"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]

    twitter  = "https://www.twitter.com/nanhung5"
    github   = "https://www.github.com/nanhung"
    linkedin = "https://www.linkedin.com/in/nhsie"
