---
title: Master thesis
author: Nan-Hung Hsieh
description: "Assessing the prevalence and exacerbations risk of influenza-associated asthma"
date: '2010-06-18'
slug: master-thesis
categories: []
tags:
  - lung
  - risk
  - influenza
  - fluctuation
---

Abstract:  
The purposes of this thesis were to assess the influenza infections-induced respiratory symptoms exacerbations risk in asthmatic subjects and to estimate the influenza epidemic-associated asthma prevalence. This study presented a probabilistic risk assessment framework apprised with reported human experimental and surveillance epidemiological data.^[[Liao CM et al. (2010) Assessing the exacerbations risk of influenza-associated chronic occupational asthma. Risk Anal. Jul;30(7):1062-75.](http://onlinelibrary.wiley.com/doi/10.1111/j.1539-6924.2010.01402.x/abstract)] Experimental studies of human influenza and influenza-induced asthma data had attempted to describe the time line of viral dynamics causing health effects of human respiratory symptoms and lung function decrements. This study reanalyzed published data by using Hill based dose-response model to construct the relationship between respiratory symptoms scores (RSS) and peak expiratory flow (PEF) of lung function for experimental human influenza infection. To detect the long-term correlations of nonstationary lung function, a detrended fluctuation analysis (DFA) was applied for quantifying the correlation of the PEF time-series history. Based on the analysis, quantifying long-term correlation exponent (α) was used as a predictor of future influenza-induced asthma exacerbations. The study also employed the DFA to detect the annual long-term effect of influenza epidemic collected from the Center for Diseases Control, Taiwan during 2001–2008.^[[Liao CM et al. (2011) Fluctuation analysis-based risk assessment for respiratory virus activity and air pollution associated asthma incidence. Sci. Tot. Environ. Aug;409(18):3325-33.](https://www.sciencedirect.com/science/article/pii/S0048969711005237)] The relationship between long-term correlation exponent of influenza epidemic and asthma admission rate was constructed to estimate the influenza-associated asthma prevalence. The results showed the respiratory symptoms scores elevation effect induced by influenza infection for both asthmatic and non-asthmatic subjects, indicating that the median exceedence risks were estimated to be 0.45 (95% confidence interval (CI): 0.12–0.82) and 0.10 (95% CI: 0.02–0.32) respectively. The DFA-based risk assessment in asthma exacerbations indicated that severe asthmatic subjects had higher influenza-associated exacerbationas risk (0.96, 95% CI: 0.88–0.99) compared with moderate (0.69, 95% CI: 0.40–0.88) and mild subjects (0.05, 95% CI: 0.01–0.13). For the quantitative fluctuation of PEF and influenza-induced asthma exacerbation risk relations, this study found that the probability of exacerbation risk can be limited to below 50% by keeping α to below 0.54. The influenza-associated asthma prevalence result found that there had significant positive association between correlation exponent influenza epidemic and asthma admission rate in Taiwan (r^2^=0.64, p < 0.05). The median exceedence risk of asthma admission rate was estimated to be 3448 (95% CI: 3388–3508) per 100,000 population. This study could provide the new method to construct the respiratory disease patient clinical records to predict and prevent the exacerbated asthma episodes during influenza infection periods. This study could also provide a better understanding for long-term effect of influenza epidemic-associated asthma prevalence.

***

#### 流感相關氣喘之盛行率及惡化風險評估

摘要：  
本論文主要目的為評估流感感染對氣喘患者所引起呼吸性症狀之惡化風險，並探討流感流行相關之氣喘盛行率。本研究以機率風險評估架構並輔以前人研究之人體實驗及流行病學調查之數據資料。藉由人體流感實驗及流感引起之氣喘資料可作為描述隨時間變化之病毒動態以及其所造成之人體呼吸性症狀與肺功能下降之健康效應，並以Hill模式為基礎之劑量反應模式架構前人研究之流感實驗之呼吸性症狀分數 (Respiratory symptoms scores) 對肺功能之尖峰呼氣流率 (Peak expiratory flow, PEF)之關係。本研究以去趨勢擾動分析(Detrended fluctuation analysis, DFA) 作為量化及偵測非穩定PEF時間數列之長期相關性。根據此分析方法，以量化PEF長期相關指數(α)可作為預測未來流感引起氣喘惡化之預測指標。本研究亦應用DFA作為偵測台灣流感流行逐年之長期效應，資料來源則為2001年至2008年台灣疾病管制局之流感調查資料。並架構流感長期之相關指數與氣喘就診率之關係，以此推估流感相關之氣喘盛行率。本研究結果顯示，由流感感染對氣喘及非氣喘族群造成呼吸性症狀上升效應之超越風險為50%時，其氣喘及非氣喘族群之超越風險分別為0.45 (95% 信賴區間：0.12–0.82)及0.10 (95% 信賴區間：0.02–0.32)。以DFA為基礎之氣喘惡化風險評估之結果指出氣喘嚴重之族群在受到流感感染後與會有較高之惡化風險 (0.96, 95% 信賴區間：0.88–0.99)，而中度氣喘與輕微氣喘之惡化風險則分別為 (0.69, 95% 信賴區間：0.40–0.88) 及 (0.05, 95% 信賴區間：0.01–0.13)。藉由量化之PEF擾動及流感引起氣喘惡化風險關係，本研究發現若維持α小於0.68，則可以使惡化風險之機率低於50%。在流感相關之氣喘盛行率結果發現，台灣流感流行之相關指數與氣喘診率具有顯著之正相關性 (r^2^=0.64, p < 0.05)，而在超越風險為50%時之氣喘就診率每十萬人口3448人 (95% 信賴區間：3388–3508)。本研究提供一套新的方法以建構呼吸性疾病患者之臨床紀錄以預測及預防流感感染期間氣喘惡化事件之發生，同時本研究亦可增加了解流感流行之長期影響相關之氣喘盛行。

