---
title: 'MCSim under R (Delay differentials example) '
summary: The advance exercise of use MCsim with R desolve package 
author: Nan-Hung Hsieh
date: '2018-04-16'
slug: mcsim-under-r-delay-differentials-example
categories: []
tags:
  - mcsim
  - R
  - desolve
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

## Prerequisites

The preliminary setting was similiar with the previous post - [MCSim under R (Unix)](https://nanhung.rbind.io/post/mcsim-under-r-unix/). The exercise was sourced from the example files in [GNU MCSim 6.0.0](http://ftp.gnu.org/gnu/mcsim/). All testing was performed in Lubuntu v17.10 with R v3.4.0. The model file `perc_delay.model` can be also found [Here](https://nanhung.rbind.io/post/perc_delay.model). In the model file, the `CalcDelay(Q_liv, tau)` was used to defind the delay variable (liver) after the time (tau). 

### load desolve package
```{R, warning=FALSE}
library(deSolve)
```

---

# Compiling Model
## Generating code for linking with R desolve package.
1. Create C model file `perc_delay.c` and R parameter initialization file `perc_delay_inits.R`

```{R, warning=FALSE}
system("mod -R perc_delay.model perc_delay.c") 
```

2. Compile the `perc_delay.c` to create `perc_delay.o` and `perc_delay_inits.so` (shared object) for dynamic loading

```{R, warning=FALSE}
system("R CMD SHLIB perc_delay.c") 
```

3. Load `perc_delay_inits.so`

```{R, warning=FALSE}
dyn.load(paste0("perc_delay",.Platform$dynlib.ext)) 
```

# Define Parameters and Variables

Due to the model parameters and variables can be generated in `perc_delay_inits.R`, we can load `initParms` and `initStats` functions in `perc_delay_inits.R` file.

```{R}
source("perc_delay_inits.R") 
```

Here, we want to redefine some input parameters. We can use the following method to replace the default value. In this case, we use the delayed time tau = 100 min, inhaled concentration = 1 ppma and exposure duration = 240 min (4 hr) as our setting.

```{R}
newParms <- c(InhMag = 1, Period=1e10, Exposure=240, tau=100)
parms <- initParms(newParms=newParms)
```

For the output variables, we select all variables as default.

```{R}
# Define the target state variables
Y <- initStates(parms=parms)
```

# Create the Exposure Matrix
The exposue matrix include two part: **Inhalation** and **Ingestion**. 
We need to generate the list of exposure by combine these two exposure matricies.

## Build inhalation exposure
We firstly set the periodic inhalation exposure scenario by using following step,

```{R}
mag <- parms["InhMag"] # Set input
period <- 1e10
inittime <- 0 # Exposure start from 0
exposuretime <- 120 # Exposure end at 2 hr

# The output time points
times <- c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 239.99, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 339.9, 340, 350) 

mintime <- min(times)
maxtime <- max(times)

# Define exposure scenarios: exposure and non-exposure
nperiods <- ceiling(maxtime / period) + 1 

col1 <- rep(inittime, 2 * nperiods)
I <- 1:length(col1)
J <- which(I %% 2 == 1)
col1[J]  <- col1[J] + (ceiling((J / 2)) - 1) * period
J <- which(I %% 2 == 0)
col1[J] <- col1[J-1] + exposuretime
PerExpo1 <- cbind(col1, rep(c(mag,0), length(col1)/2))

# The matrix of inhalation exposure
PerExpo1
```
Here, we can see the setting expoure is start at 0 and 1e10 then stop at 240 and 1e10, respectively.

## Plot exposure scenario
The exposure scenario can be visualized by following method,  
```{R}
plot(PerExpo1[1:2,], type = "s", xlim=c(0,maxtime), main = "C_inh", xlab = "Time (min)")
```

# Build Ingestion dose Matrix
## Setting 1: without constant exposure
Here we generate the matrix for ingestion dose,

```{R}
mag1 <- 0 # the backgroud exposure dose = 0
IngDose <- rbind(c(min(times), mag1), c(max(times) + 1, 0))
IngDose
```
As above, we can find that there is no given exposure dose from start to the end (0 to 351 min). We can generate the list of exposure by combine the `PerExpo` and `IngDose`. After that, we can further apply the solver for delay differential equations `dede` from desolve package.

```{R}
# Add code to implement in the inputs built into the model.
Forcings1 <- list(PerExpo1, IngDose)
out1 <- dede(Y, times, func="derivs", parms=parms, dllname="perc_delay",
            initfunc="initmod", nout=length(Outputs), outnames=Outputs,
            initforc="initforc",
            fcontrol=list(method="constant", rule=1, f=0),
            forcings=Forcings1)
```

## Setting 2: with constant exposure
Here, we assume the constant exposure concentration = **0.2 ppm**.

```{R}
PerExpo2 <- PerExpo1
PerExpo2[2,2] <- 0.2 # 0.2 ppm as constant exposure 
Forcings2 <- list(PerExpo2, IngDose)
out2 <- dede(Y, times, func="derivs", parms=parms, dllname="perc_delay",
            initfunc="initmod", nout=length(Outputs), outnames=Outputs,
            initforc="initforc",
            fcontrol=list(method="constant"),
            forcings=Forcings2)
```

We can do the inspection to check the output result by total quantity as, 

```{R}
stop_point <- which(out1[,"time"] == 240)
```

Then, check the exposure dose without constant dose. The output should approximate to 0.5 (ppm).

```{R}
out1[,"Q_tot"][stop_point] / (240 * 5.6 * 0.006778) 
```

Check the exposure dose with constant dose. The output should approximate to 0.6 (ppm).

```{R}
out2[,"Q_tot"][stop_point] / (240 * 5.6 * 0.006778)
```

# Visualization
Plot and compare the simulation result

```{R}
par(mfrow = c(3,5), mar = c(4,2,3,1))
for(i in 2:ncol(out1)){
  plot(out2[,1], out2[,i], type="l", xlab = "Time", ylab="" , 
       col = 2, main = names(out1[3,i])) 
  lines(out1[,1], out1[,i], type = "l", col = 3, lty = 2)
}
```

The green dashed line is periodic exposure without constant level. The red solid line is periodic exposure with constant level The simulation of delay output can obtain in **old_Q_liv**, **Q_met** and **Pct_metabolized**. 
